# Generated by Django 4.0.3 on 2022-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='desc',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scout',
            name='name',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scout',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
